// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWXOwa4UXCTqR-KmVGBXihWCAD9B2HKOY',
    appId: '1:249666075575:web:b642f4e9a7afc84a914632',
    messagingSenderId: '249666075575',
    projectId: 'nsync-fb772',
    authDomain: 'nsync-fb772.firebaseapp.com',
    storageBucket: 'nsync-fb772.firebasestorage.app',
    measurementId: 'G-9KQYF5LQWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3s81v1RuPHMClsy-NuDMCMer3l0u1Z0',
    appId: '1:249666075575:android:65cf18e206401076914632',
    messagingSenderId: '249666075575',
    projectId: 'nsync-fb772',
    storageBucket: 'nsync-fb772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq41zKDWFyhsJ3x2OOu53e2CysbybXoYY',
    appId: '1:249666075575:ios:30bd3b45dd668080914632',
    messagingSenderId: '249666075575',
    projectId: 'nsync-fb772',
    storageBucket: 'nsync-fb772.firebasestorage.app',
    iosBundleId: 'com.example.nsyncAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq41zKDWFyhsJ3x2OOu53e2CysbybXoYY',
    appId: '1:249666075575:ios:30bd3b45dd668080914632',
    messagingSenderId: '249666075575',
    projectId: 'nsync-fb772',
    storageBucket: 'nsync-fb772.firebasestorage.app',
    iosBundleId: 'com.example.nsyncAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWXOwa4UXCTqR-KmVGBXihWCAD9B2HKOY',
    appId: '1:249666075575:web:5b936dd8db920a43914632',
    messagingSenderId: '249666075575',
    projectId: 'nsync-fb772',
    authDomain: 'nsync-fb772.firebaseapp.com',
    storageBucket: 'nsync-fb772.firebasestorage.app',
    measurementId: 'G-K2403DKS6J',
  );
}
