name: nsync_student
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  supabase_flutter: ^2.8.3
=======
  firebase_core: ^3.10.1
  supabase_flutter: ^2.8.3
  cherry_toast: ^1.11.0
  google_fonts: ^6.2.1
>>>>>>> e5e54fd27d99b8f04e92517dfd4a8efc5fcb43fe

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
